# serverless.yml

#组件信息
component: scf # (必选) 组件名称，在该实例中为scf
name: jdscript # (必选) 组件实例名称。

#组件参数配置
inputs:
  name: scf-${name} # 云函数名称，默认为 ${name}-${stage}-${app}
  enableRoleAuth: true # 默认会尝试创建 SCF_QcsRole 角色，如果不需要配置成 false 即可
  src: ./
  handler: index.main_handler #入口
  runtime: Nodejs12.16 # 运行环境 默认 Nodejs12.16
  region: ap-guangzhou # 函数所在区域
  description: This is a function in ${app} application.
  memorySize: 128 # 内存大小，单位MB
  timeout: 86400 # 超时时间，单位秒
  asyncRunEnable: true # 是否启用异步执行
  events: #触发器
    - timer: #抢京豆#送豆得豆#京东手机狂欢城活动#
        parameters:
          name: 1jd_bean_sign
          cronExpression: "30 0 0,12,14 * * * *"
          enable: true
          argument: jd_bean_home&jd_sendBeans&jd_carnivalcity&&
    - timer: #宠汪汪积分兑换奖品##
        parameters:
          name: 2cfdtx_xtg
          cronExpression: "0 0 0,12,14-22/2 * * * *"
          enable: true
          argument: jd_joy_reward&
    - timer: #京东月资产变动通知#京东资产变动通知#点点券红包####
        parameters:
          name: 3jd_try
          cronExpression: "0 30 7 * * * *"
          enable: true
          argument: jd_all_bean_change&jd_bean_change&jd_necklace&
    - timer: #京喜财富岛#财富岛气球####
        parameters:
          name: 4jd_joy-park
          cronExpression: "2 15,45 7,8-23/2 * * * *"
          enable: true
          argument: jd_cfd&jd_cfd_loop&&&&
    - timer: #东东水果#jd宠汪汪#宠汪汪喂食#ts#取关主播#
        parameters:
          name: 5joy_park
          cronExpression: "40,1 0-23/1 * * *"
          enable: true
          argument: jd_fruit&jd_joy&jd_joy_feedPets&jd_IndustryLottery&TS_USER_AGENTS&jd_unsubscriLive
    - timer: #京东到家鲜豆#京东到家果园任务#推金币#
        parameters:
          name: 6jd_morningSc
          cronExpression: "0 10,20,30,40,50 0-23/1 * * * *"
          enable: true
          argument: jd_dj_bean&jd_dj_fruit&jd_tuijinbi&
    - timer: #天天优惠大乐透#宠汪汪偷好友积分与狗粮#京喜工厂开团#
        parameters:
          name: 7jd_mohe
          cronExpression: "1,1 0-23/1 * * *"
          enable: true
          argument: jd_DrawEntrance&jd_joy_run&jd_dreamFactory_tuan&jddj_fruit_code
    - timer: #京东到家鲜豆#京东到家果园#京东到家果园水车收水滴#京东到家鲜豆庄园收水#京东到家鲜豆庄园脚本#
        parameters:
          name: 8jd_cfdqiqiu
          cronExpression: "1,30 0-23/1 * * *"
          enable: true
          argument: jddj_bean&jddj_fruit&jddj_fruit_collectWater&jddj_getPoints&jddj_plantBeans&
    - timer: #财富岛红包#京喜签到#
        parameters:
          name: 9jd_lsj
          cronExpression: "0 14,44 9,8-23/1 * * * *"
          enable: true
          argument: jx_cfdtx&jx_sign&RanDongXiaJi
    - timer: #宠旺旺比赛###
        parameters:
          name: 10gua-opencard
          cronExpression: "0 13,43 9,8-23/1 * * * *"
          enable: true
          argument: jd_joy_run&
  environment: #  环境变量
    variables: #  环境变量对象
      AAA: BBB # 不要删除，用来格式化对齐追加的变量的
